### ISSUE TITLE
Green bug

### ISSUE THREAD

**Issue by bokov** [bokov-andrew/bombdodger#1]
https://github.com/bokov-andrew/bombdodger/blob/6543c2eeb94a6381a5fd69dd8b8e6c3553854d36/bombdodger.py#L43

The above line is where your problem with drawing darkgreen and seagreen originates.

What does your book say `square.grid()` does?

Should that be done only for the `else`  part (i.e. only the `"green" ` one) or for all of them?

**Comment by bokov-andrew** [comment]
poo poo
